POLICE_CODES = { 
    "IMPORTANT": { 
        "10-4": "Acknowledgment / Message Received", 
        "10-20": "Location", 
        "10-33": "EMERGENCY - OFFICER NEEDS HELP", 
        "10-78": "Need Assistance", 
        "10-80": "Pursuit in Progress", 
        "10-99": "Wanted/Stolen Record", 
        "Signal 100": "Emergency Radio Traffic Only" 
    }, 
    "GENERAL_10_CODES": { 
        "10-0": "Caution", 
        "10-1": "Unable to Copy / Poor Reception", 
        "10-2": "Signals Good", 
        "10-3": "Stop Transmitting", 
        "10-5": "Relay To", 
        "10-6": "Busy, Stand By", 
        "10-7": "Out of Service", 
        "10-8": "In Service", 
        "10-9": "Repeat Message", 
        "10-10": "Fight in Progress", 
        "10-11": "Dog Case", 
        "10-12": "Stand By / Visitors Present", 
        "10-13": "Weather/Road Report", 
        "10-14": "Prowler Report", 
        "10-15": "Civil Disturbance", 
        "10-16": "Domestic Disturbance", 
        "10-17": "Meet Complainant", 
        "10-18": "Quickly / Urgent", 
        "10-19": "Return to Station", 
        "10-21": "Call by Telephone", 
        "10-22": "Disregard", 
        "10-23": "Arrived at Scene", 
        "10-25": "Report in Person to", 
        "10-26": "Detaining Subject", 
        "10-27": "Drivers License Info", 
        "10-28": "Vehicle Registration Info", 
        "10-29": "Check for Wanted", 
        "10-30": "Illegal Use of Radio", 
        "10-31": "Crime in Progress", 
        "10-32": "Person with Weapon", 
        "10-34": "Riot", 
        "10-35": "Major Crime Alert", 
        "10-36": "Correct Time", 
        "10-37": "Suspicious Vehicle", 
        "10-38": "Stopping Suspicious Vehicle", 
        "10-39": "Urgent - Use Light/Siren", 
        "10-41": "Beginning Duty", 
        "10-42": "Ending Duty", 
        "10-43": "Information", 
        "10-44": "Permission to Leave", 
        "10-45": "Animal Carcass", 
        "10-46": "Assist Motorist", 
        "10-49": "Traffic Signal Out", 
        "10-50": "Accident (F, PI, PD)", 
        "10-51": "Wrecker Needed", 
        "10-52": "Ambulance Needed", 
        "10-53": "Road Blocked", 
        "10-54": "Livestock on Highway", 
        "10-55": "Intoxicated Driver (DUI)", 
        "10-56": "Intoxicated Pedestrian", 
        "10-57": "Hit and Run", 
        "10-58": "Direct Traffic", 
        "10-59": "Convoy or Escort", 
        "10-60": "Squad in Vicinity", 
        "10-61": "Personnel in Vicinity", 
        "10-62": "Reply to Message", 
        "10-63": "Prepare to Copy", 
        "10-64": "Local Message", 
        "10-65": "Net Message Assignment", 
        "10-66": "Message Cancellation", 
        "10-67": "Clear for Net Message", 
        "10-68": "Dispatch Information", 
        "10-69": "Message Received", 
        "10-70": "Fire Alarm", 
        "10-71": "Advise Nature of Fire", 
        "10-72": "Report Progress on Fire", 
        "10-73": "Smoke Report", 
        "10-74": "Negative", 
        "10-75": "In Contact With", 
        "10-76": "En Route", 
        "10-77": "ETA", 
        "10-79": "Notify Coroner", 
        "10-81": "Breathalyzer Report", 
        "10-82": "Reserve Lodging", 
        "10-84": "If Meeting, Advise Time", 
        "10-85": "Delayed due to...", 
        "10-87": "Pick Up Checks", 
        "10-88": "Present Phone Number", 
        "10-89": "Bomb Threat", 
        "10-90": "Bank Alarm", 
        "10-91": "Pick Up Prisoner", 
        "10-92": "Improperly Parked Vehicle", 
        "10-93": "Blockage", 
        "10-94": "Drag Racing", 
        "10-95": "Prisoner in Custody", 
        "10-96": "Mental Subject", 
        "10-97": "Check Signal", 
        "10-98": "Prison Break" 
    } 
}
